/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokenizedBallotSol from "./TokenizedBallot.sol";
export type { tokenizedBallotSol };
export type { Lottery } from "./Lottery";
export type { LotteryToken } from "./LotteryToken";
export type { MyERC20 } from "./MyERC20";
export type { MyERC721 } from "./MyERC721";
export type { MyToken } from "./MyToken";
export type { TokenSale } from "./TokenSale";
