/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMyVotingToken,
  IMyVotingTokenInterface,
} from "../../../contracts/TokenizedBallot.sol/IMyVotingToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "getPastVotes",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMyVotingToken__factory {
  static readonly abi = _abi;
  static createInterface(): IMyVotingTokenInterface {
    return new utils.Interface(_abi) as IMyVotingTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMyVotingToken {
    return new Contract(address, _abi, signerOrProvider) as IMyVotingToken;
  }
}
